### ISSUE TITLE
The issue of dataset formats

### ISSUE THREAD

**Issue by jackweiwang** [Megvii-BaseDetection/TreeFilter-Torch#4]
C.img_root_folder = "/home/ww/data/Datasets/Segmentation/VOC2012_AUG/"
C.gt_root_folder = "/home/ww/data/Datasets/Segmentation/VOC2012_AUG/"
C.train_source = "/home/ww/data/Datasets/Segmentation/VOC2012_AUG/config/train.txt"
C.eval_source = "/home/ww/data/Datasets/Segmentation/VOC2012_AUG/config/val.txt"
C.test_source = "/home/ww/data/Datasets/Segmentation/VOC2012_AUG/config/voc12_test.txt"

but VOC2012 directory structure 

Annotations
ImageSets
JPEGImages
Segmentation Class
Segmentation Object

**Comment by StevenGrove** [comment]
You can generate the annotations by following this [instruction](https://github.com/ycszen/TorchSeg#training).

**Comment by jackweiwang** [comment]
thank  you

**Comment by cvprkang** [comment]
> You can generate the annotations by following this [instruction](https://github.com/ycszen/TorchSeg#training).

您好，不好意思打扰您，我对此不太清楚，请问可不可以使用谷歌网盘直接分享相关数据集文件，或者更细节的解释如何用VOC2012 原始文件结构生成您用的数据集文件结构？

**Comment by StevenGrove** [comment]
Please refer to https://drive.google.com/file/d/1PbHzvBx3vqqw_OQ10e6ZfnOCxHiZ-FJH/view?usp=sharing.
