### ISSUE TITLE
Does the code support 3D input?

### ISSUE THREAD

**Issue by zhangfb** [Megvii-BaseDetection/TreeFilter-Torch#5]
Hi, thank you for your extraordinary work !  I wonder if I could use your code to process 3D Volume.

I have a 3D input (ZxHxW instead of HxW for 2D image), whose size during training in pytorch is BxCxZxHxW. So I wonder if I could just modify few details in your code to run 3D input.

1. Modify the index and weight to 3D in **MinimumSpanningTree**
Can I just add the extra_index and weight_extra for the index and weight, then  put them into **mst** to generate a tree? 
![image](https://user-images.githubusercontent.com/34835701/72033708-095d9080-32ce-11ea-860b-426ee6bf6f8b.png)

2. Use **bfs** with max_adj_per_vertex=6
Will the bfs work properly by changing max_adj_per_vertex to 6 for 3D Volume?
![image](https://user-images.githubusercontent.com/34835701/72034041-e5e71580-32ce-11ea-9d54-3462409d440b.png)

3. Is **refine** compatible with 3D input ?
The feature_in in the forward method of TreeFilter2D is reshaped to (B*Groups, C//Groups, -1). So is it also compatible with a shaped 3D input?

**Comment by StevenGrove** [comment]
Yes. As you mentioned, the provided cuda kernels (i.e., "mst", "bfs" and "refine") are compatible with any dimension of input features by using the "reshape" operation. You just need to follow the steps you proposed to modify the python code.

**Comment by zhangfb** [comment]
Thanks a lot!!!
