### ISSUE TITLE
Implementation on V100

### ISSUE THREAD

**Issue by GewelsJI** [Megvii-BaseDetection/TreeFilter-Torch#8]
Hi,

Thank you for providing such a nice paper. I have a question here. The default setting indicates the implementation on pytorch1.2.

But, if possible, could this library (TreeFilter-Torch/furnace/kernels/lib_tree_filter) be implemented on V100 GPU? Are there any modifications?

**Comment by StevenGrove** [comment]
Yes, it can run on V100 GPU. What issues did you have when compiling the code?

**Comment by GewelsJI** [comment]
I guess the issue coming from the CUDA version. What's your version of CUDA and pytorch on V100?

**Comment by StevenGrove** [comment]
I have updated the code. Now it can support cuda 11 and up to pytorch 1.12.1.

**Comment by GewelsJI** [comment]
@StevenGrove Thank you again.
